export const members = [
    {
        id:1,
        firstName: "Jestin",
        middleName: "",
        lastName: "Kuriakose",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 0,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
    {
        id:2,
        firstName: "Antu",
        middleName: "",
        lastName: "Sunny",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 5,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
    {
        id:3,
        firstName: "Benson",
        middleName: "",
        lastName: "Mathai",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 23,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
    {
        id:4,
        firstName: "Aby",
        middleName: "",
        lastName: "Thomas",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 23,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
    {
        id:5,
        firstName: "Bincy",
        middleName: "",
        lastName: "Antu",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 23,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
    {
        id:6,
        firstName: "Jeromie",
        middleName: "",
        lastName: "Samuel",
        address1: "79 Florence Ave",
        address2: "Unit A",
        city: "Kitchener",
        province: "ON",
        postalCode: "N2A2K9",
        country: "Canada",
        email1: "jestink@live.com",
        email2: "",
        phone1: "5197220063",
        phone2: "",
        active: true,
        sex: "M",
        dob: "1992-02-28", 
        doj: "2010-02-12",
        spouse: 23,
        children1: "",
        children2: "",
        children3: "",
        children4: ""
    },
]

export const tithes = [
    {
        id:1,
        member: 2,
        date: "2023-03-10",
        amount: 380
    },
    {
        id:2,
        member: 1,
        date: "2023-04-03",
        amount: 175
    },
    {
        id:3,
        member: 6,
        date: "2023-02-02",
        amount: 420
    },
    {
        id:4,
        member: 4,
        date: "2023-01-30",
        amount: 90
    },
    {
        id:5,
        member: 3,
        date: "2023-01-19",
        amount: 10
    },
    {
        id:6,
        member: 5,
        date: "2023-01-10",
        amount: 190
    },
    {
        id:7,
        member: 1,
        date: "2023-02-10",
        amount: 450
    },
    {
        id:8,
        member: 6,
        date: "2023-03-22",
        amount: 320
    },
    {
        id:9,
        member: 2,
        date: "2023-03-14",
        amount: 150
    },
]

export default { members, tithes }